[package]
name = "tokio-test"
version = "0.2.0"
authors = ["Douglas Anderson <hockeybuggy@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
